# Setup
title:               "day"
tagline:             "A simple blog"
description:         'You can only write one article a day. GitHub <a href="https://github.com/ongaeshi/day">ongaeshi/day</a>.'
url:                 https://ongaeshi.github.io
baseurl:             "/day"
paginate:            30
permalink:           pretty
timezone:            Asia/Tokyo

# About/contact
author:
  name:              yourname
  url:               https://yourname.example.com
  email:             youname@example.com

# Twitter card
# twitter_username:    yourname

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
